### ISSUE TITLE
Exception: Frog Move nach tot

### ISSUE THREAD

**Issue by jastrow** [jastrow/FroggerMultiplayer#21]
Wenn tot und tastatureingabe, wird ein fehler geworfen.
Frosch movement wurde stillgelegt (sended bei tot keine daten mehr)

**Comment by ghost** [comment]
erledigt habe ne bool eingefügt der schaut ob das Spiel läuft // wenn der Frosch stirbt nimmt die Szene keine Trigger mehr entgegen
