### ISSUE TITLE
Mneü blockieren wenn Spiel läuft

### ISSUE THREAD

**Issue by jastrow** [jastrow/FroggerMultiplayer#27]
Handling mit dem Multithreading scheint mir zu unhandlich.
Problem, mann kann mehrmals hintereineander das Spiel starten durch das Menü.
Das Spiel läuft dann viel schneller, oder keine Hindernisse, solange die alte Zeit nicht erreicht wurde. (da mehrere timer-threads)
Daher bitte das Menü blocken, wenn das Spiel gerade läuft (bis Zeit um).

**Comment by ghost** [comment]
entfernen kann ich das Menü leider nicht da ich es zur Laufzeit nicht neu rendern kann, allerdings habe ich das dahinterliegende Event abgefangen und es wird jetzt nur noch behandelt wenn die Zeit abgelaufen ist // der Frosch stirbt bzw. der Spieler gewinnt
