### ISSUE TITLE
Auftritt & Prezi 

### ISSUE THREAD

**Issue by jastrow** [jastrow/FroggerMultiplayer#29]
1) Vorstellung des Spiels und aller Elemente (Salim)
2) Prezi starten
3) Hallo
4) UML (gesamt)
5) UML (Observer Grundstruktur MVC)
5b) Configuration zeigen
6) UML (Scene & DB Highscore)
7) UML (Models Gamelogik)
8) Statistiken
Anzahl Zeilen Code
Anzahl Emails
Anzahl WhatsApp Nachrichten
Anzahl Issues (Als bild zeigen!)
Anzahl Skype-Meetings

9) Problemzonen
 Manuel + Mike: ConcurrentLinkedQueue (Laufzeit)
 Manuel: Canvas - Lösung statt GridPane
 Mike: Multithreading & Debugging
 Salim: Frosch auf den Baum zu bekommen (mitreiten) & Random + Fluss der Bäume

10) Ente

**Comment by slimouGit** [comment]
Anzahl Zeilen Code = 3803

**Comment by slimouGit** [comment]
Anzahl Emails = 156

**Comment by slimouGit** [comment]
Anzahl WhatsApp Nachrichten = 210

**Comment by slimouGit** [comment]
Anzahl Skype-Meetings = 19

**Comment by slimouGit** [comment]
Anzahl Issues = 32 und 247 Commits
